### ISSUE TITLE
UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by NickEdmunds** [DeepRank/iScore#33]
**Describe the bug**
A clear and concise description of what the bug is. UnpicklingError: could not find MARK occurs when attempting to run iScore.predict using the trained model.

**Environment:**
- OS system: Ubuntu
- Version: 20.04
- Branch commit ID: 
- Inputs:

**To Reproduce**
Steps/commands to reproduce the behaviour:
 1. created pdb and pssm folders under iScore/test directory
 2. typed either iScore.predict or mpiexec -n iScore.predict.mpi within the test directory (both gave the same error)
 3. 

**Expected Results**
A. Expected the creating of iScore.predict.txt file

**Actual Results or Error Info**
nick@nick-HP-ZBook-15-G5:~/iScore/test$ iScore.predict
/home/nick/.local/lib/python3.8/site-packages/skcuda/cublas.py:284: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
Reusing graphs in ./graph/
Reusing kernels in ./kernel/
Traceback (most recent call last):
  File "/home/nick/.local/bin/iScore.predict", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/nick/iScore/bin/iScore.predict", line 68, in <module>
    iscore_svm(load_model=None,package_name=args.archive,maxlen=args.maxlen,testID=args.ground_truth)
  File "/home/nick/iScore/iScore/graphrank/rank.py", line 400, in iscore_svm
    testdata = DataSet(trainID,Kfile,maxlen,testID=testID)
  File "/home/nick/iScore/iScore/graphrank/rank.py", line 39, in __init__
    self.get_K_matrix()
  File "/home/nick/iScore/iScore/graphrank/rank.py", line 104, in get_K_matrix
    K.update(pickle.load(open(f,'rb')))
_pickle.UnpicklingError: could not find MARK

**Additional Context**
Example of pdb and pssm files attached.
[1084_TS029_1o.zip](https://github.com/DeepRank/iScore/files/8425948/1084_TS029_1o.zip)

**Comment by NicoRenaud** [comment]
Thanks for filling in the issue we will look into it
