### ISSUE TITLE
issues of iscore doc

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/iScore#9]
I am following iScore workflow and got the error message below:

(base) [lixue@alcazar test]$ `mpiexec -n 2 iScore.predict.mpi --archive ../train/training_set.tar.gz`
Warning : pycuda not found
Warning : scikit-cuda not found
Warning : pycuda not found
Warning : scikit-cuda not found
Traceback (most recent call last):
  File "/home/lixue/tools/iScore/bin/iScore.predict.mpi", line 81, in <module>
    iscore_svm(load_model=None,package_name=args.archive,testID=args.ground_truth)
  File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 401, in iscore_svm
    testdata = DataSet(trainID,Kfile,maxlen,testID=testID)
  File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 39, in __init__
    self.get_K_matrix()
  File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 112, in get_K_matrix
    key = list(K.keys())[1]
IndexError: list index out of range

**Comment by CunliangGeng** [comment]
README updated. Close it now.
